#!/bin/bash
TARGETNODE=
NAME="-sname entop"
COOKIE="-setcookie cookie"

function usage() {
    echo -e "Usage: ./entop <TARGETNODE> [-name <NAME>|-sname <SNAME>] [-setcookie <COOKIE>]"
}

if [[ $# -lt 1 ]]; then
    usage
    exit 1
fi

TARGETNODE=$1
shift


for ARG in $@;
do
    case $ARG in
	"-name")
	    NAME=; ;;
	"-sname")
	    NAME=; ;;
	"-setcookie")
	    COOKIE=; ;;
    esac
done

erl -noinput -hidden -pa ebin/ -pa ../cecho/ebin/ +A 20 +Bc -eval "entop:start('${TARGETNODE}')" $NAME $COOKIE $@

CODE=$?
if [[ $CODE -eq 101 ]]; then
    echo "Unable to connect to '${TARGETNODE}', check nodename, cookie and network."
    exit 2
elif [[ $CODE -gt 0 ]]; then
    echo "Something wrong. Code: ${CODE}"
    exit $CODE
fi
