#!/bin/bash
##==============================================================================
## Copyright (c) 2017, Mazen Harake
## All rights reserved.
##
## Redistribution and use in source and binary forms, with or without
## modification, are permitted provided that the following conditions are met:
##
##     * Redistributions of source code must retain the above copyright notice,
##       this list of conditions and the following disclaimer.
##     * Redistributions in binary form must reproduce the above copyright
##       notice, this list of conditions and the following disclaimer in the
##       documentation and/or other materials provided with the distribution.
##
## THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
## AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
## IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
## ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
## LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
## CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
## SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
## INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
## CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
## ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
## POSSIBILITY OF SUCH DAMAGE.
##==============================================================================

## Shell script for running entop. See the function usage() for instructions.

function usage() {
    echo -e "Usage: ./entop <TARGETNODE> [<COOKIE>]"
}

if [[ $# -lt 1 ]]; then
    usage
    exit 1
fi

TARGETNODE=$1
shift

COOKIE=${1-undefined}
shift

if [[ -d _build ]] ; then
  PATHS="-pa _build/default/lib/entop/ebin -pa _build/default/lib/cecho/ebin"
else
  PATHS=""
fi

erl -noinput -hidden $PATHS +A 20 +Bc \
    -eval "entop:main(['${TARGETNODE}','${COOKIE}'])." "$@"

CODE=$?
if [[ $CODE -eq 101 ]]; then
    echo "Unable to connect to '${TARGETNODE}', check nodename, cookie and network."
    exit 2
elif [[ $CODE -gt 0 ]]; then
    echo "Something wrong. Code: ${CODE}"
    exit $CODE
fi
