#!/home/mazen/lib/erlang-14A/bin/escript
%%! -noinput -hidden -pa ebin/ -pa ../cecho/ebin/ -sname ntop -setcookie cookie +A 50
main([Node]) -> 
    ntop:start(list_to_atom(Node), []),
    erlang:halt(1);
main(_) -> 
    io:format("Usage: ./ntop <NODE>").
	   
